### PR TITLE
added address field in student

### PR DESCRIPTION
**Pull request by somarajukiran**
hai raj;

i done my task kindly verify the code .

and give approve to pull request

### CODE REVIEW

**Review by rajssdtech — CHANGES_REQUESTED** [review]
Mr kiran good work please try to add phone number field also

**Comment by somarajukiran** [comment]
hai 
added mobileNo

**Review by rajssdtech — APPROVED** [review]
good work

**Comment by somarajukiran** [comment]
my code merger release 1

**Pull request merged**
